Tue Nov 01 12:39:20 ART 2016 : Apache Derby Network Server - 10.8.3.2 - (1557835) se ha iniciado y está listo para aceptar conexiones en el puerto 1527
----------------------------------------------------------------
Tue Nov 01 12:39:20 ART 2016:
 Arrancando Derby versión The Apache Software Foundation - Apache Derby - 10.8.3.2 - (1557835): instancia a816c00e-0158-208b-751b-000054ca45d5 
en el directorio de base de datos /media/aaron/AARON/Base de datos/Registro_Automotriz  con el cargador de clases sun.misc.Launcher$AppClassLoader@20e90906

java.vendor=Oracle Corporation
java.runtime.version=1.7.0_79-b15
user.dir=/home/aaron/Escritorio/jdk1.7.0_79/db
os.name=Linux
os.arch=amd64
os.version=4.4.0-31-generic
derby.system.home=/media/aaron/AARON/Base de datos
Cargador de clases de base de datos iniciado - derby.database.classpath=''
----------------------------------------------------------------
Tue Nov 01 12:39:23 ART 2016:
Cerrando la instancia a816c00e-0158-208b-751b-000054ca45d5 en el directorio de base de datos /media/aaron/AARON/Base de datos/Registro_Automotriz con cargador de clases sun.misc.Launcher$AppClassLoader@20e90906
Tue Nov 01 12:39:30 ART 2016 Thread[DRDAConnThread_4,5,main] (DATABASE = Registro_Automotriz), (DRDAID = {2}), Conclusión de la base de datos 'Registro_Automotriz'.
Tue Nov 01 12:54:50 ART 2016 Thread[DRDAConnThread_3,5,main] Cleanup action starting
java.sql.SQLException: Base de datos 'bdConcesionario' no encontrada.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Base de datos 'bdConcesionario' no encontrada.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Base de datos 'bdConcesionario' no encontrada.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Tue Nov 01 12:54:50 ART 2016 Thread[DRDAConnThread_3,5,main] (DATABASE = bdConcesionario), (DRDAID = {3}), Base de datos 'bdConcesionario' no encontrada.
----------------------------------------------------------------
Tue Nov 01 17:30:34 ART 2016: cerrando motor de Derby
----------------------------------------------------------------
